project:
  type: website

website:
  title: "Simply Foot"
  navbar:
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Gareth1995
      - icon: twitter
        href: https://x.com/Gareth_FDS
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

